### ISSUE TITLE
Doesn't traverse through row 7 or 8 at all

### ISSUE THREAD

**Issue by Khobaka** [CyrusVatandoost/search-battle#35]
I tried putting a treasure on these rows and I couldn't detect them.

**Comment by CyrusVatandoost** [comment]
Does the Treasure show on the Display? Do you have sample code of what you changed?

**Comment by Khobaka** [comment]
Yes, the treasure shown in the display.

I used this code:
	
	for(int j = 0; j < blocks.length; j++)
              for(int i = 0; i < blocks[0].length; i++)
                    if(blocks[j][i] instanceof Treasure)
                           System.out.print("Tresure at Column " + j + " Row " + i + "\n");

![image](https://user-images.githubusercontent.com/36791541/41817866-03b1c25a-77d6-11e8-9eff-9fc366d74cba.png)
This was my map 

and only this results shown 

![image](https://user-images.githubusercontent.com/36791541/41817868-2095538c-77d6-11e8-8ef7-536a8a22db6f.png)
